# python questions

# write a program to print a digit of a given no. 


In [4]:
n=int(input("enter the no. \n"))
c=0
while(n!=0):
    print(n%10)
    n=n//10
    c=c+1
print("the no. of digit of a no. is= ",c)

 

enter the no. 
9876543210
0
1
2
3
4
5
6
7
8
9
the no. of digit of a no. is=  10


##  write a program to print the sum of digit of  a given no.

In [1]:
n=int(input("enter the no.\n"))
s=0
c=0
while(n!=0):
    a=n%10
    print(a)
    
    s=s+a
    n=n//10
    c=c+1
print("the sum of the digit of a no. is= ",s)
print("the no. of digit of a no. is =",c)


enter the no.
987654321
1
2
3
4
5
6
7
8
9
the sum of the digit of a no. is=  45
the no. of digit of a no. is = 9


# write a program to print the greatest no. with in a no.


In [8]:
n=int(input("enter a number \n"))
max=n%10
while(n!=0):
    a=n%10
    n=n//10
    if(max>a):
        max=max
    else:
    
        max=a
print("the maximum of a given no. is =",max)  


enter a number 
258
the maximum of a given no. is = 8


# wap to print the greatest and counting of greater no.

In [17]:
n=int(input("enter a number \n"))
b=n
max=n%10
c=0
while(n!=0):
    a=n%10
    n=n//10
    if(max>a):
        max=max
    else:
        max=a


print("the maximum of a given no. is=",max)
n=b
while(n!=0):
    a=n%10
    n=n//10
    if(max==a):
        c=c+1
    else:
        pass
print("the maximum of counting is =",c)

enter a number 
12333210
the maximum of a given no. is= 3
the maximum of counting is = 3


# again 

In [37]:
n=int(input("enter a number \n"))

max=n%10
c=0
while(n!=0):
    a=n%10
    n=n//10
    if(max>=a):
        max=max
        if(max==a):
            c=c+1
    else:
        max=a
        c=1


print("the maximum of a given no. is=",max)
print("the maximum of the digit is =",c)

enter a number 
898989898989899999999
the maximum of a given no. is= 9
the maximum of the digit is = 14


# wap to print 10 no. sum,avg,max,min

In [7]:
n=int(input("enter the no"))
i=0
s=0
c=0
while(i<n):
    a=int(input("enter the no "))
    if(c==0):
        max=a
        min=a
    s=s+a   
    if(max>=a):
        max=max
    else:
        max=a
    if(min<=a):
        min=min
    else:
        min=a
        
    c=c+1
    i=i+1
avg=s/n    
print("the sum is =",s)
print("the max is ",  max)
print("the avg is ", avg)
print("the min is " , min)

    
    
    



enter the no9
enter the no 9
enter the no 8
enter the no 7
enter the no 6
enter the no 5
enter the no 4
enter the no 3
enter the no 2
enter the no 0
the sum is = 44
the max is  9
the avg is  4.888888888888889
the min is  0


## wap to print the patter 
 ### **1
 ### *22
 ### 333

In [28]:
for outer in range(1,4):
    for space in range(1,4-outer):
        print(" ",end=" ")
    for inner in range(1,outer +1):
        print(outer,end=" ")
    print("")


    1 
  2 2 
3 3 3 


# wap to print the fibanoic series

In [21]:
n=int(input("enter the no. you want to print "))
a=0
b=1
print(a,b)
while(n!=0):
    c=a+b
    a=b
    b=c
    print(c)
    n=n-1
    

enter the no. you want to print 5
0 1
1
2
3
5
8


## wap to print the 
###    1
###  1 2 1
### 1 2 3 2 1

In [3]:
for r in range(1,4):
    for space in range(1,4-r):
        print(" ",end="")
    for c in range(1,r+1):
        print(c,end="")
    for d in range(r-1,0,-1):
        print(d,end="")
    print()
       

  1
 121
12321


In [10]:
m=0
for r in range(0,10):
    for c in range(0,10):
        for l in range(0,10):
            for k in range(0,10):
                s=r+c+l+k
                if(s==9):
                    m=m+1
                    print(r,c,l,k)
                    
print(m)                   
                    

0 0 0 9
0 0 1 8
0 0 2 7
0 0 3 6
0 0 4 5
0 0 5 4
0 0 6 3
0 0 7 2
0 0 8 1
0 0 9 0
0 1 0 8
0 1 1 7
0 1 2 6
0 1 3 5
0 1 4 4
0 1 5 3
0 1 6 2
0 1 7 1
0 1 8 0
0 2 0 7
0 2 1 6
0 2 2 5
0 2 3 4
0 2 4 3
0 2 5 2
0 2 6 1
0 2 7 0
0 3 0 6
0 3 1 5
0 3 2 4
0 3 3 3
0 3 4 2
0 3 5 1
0 3 6 0
0 4 0 5
0 4 1 4
0 4 2 3
0 4 3 2
0 4 4 1
0 4 5 0
0 5 0 4
0 5 1 3
0 5 2 2
0 5 3 1
0 5 4 0
0 6 0 3
0 6 1 2
0 6 2 1
0 6 3 0
0 7 0 2
0 7 1 1
0 7 2 0
0 8 0 1
0 8 1 0
0 9 0 0
1 0 0 8
1 0 1 7
1 0 2 6
1 0 3 5
1 0 4 4
1 0 5 3
1 0 6 2
1 0 7 1
1 0 8 0
1 1 0 7
1 1 1 6
1 1 2 5
1 1 3 4
1 1 4 3
1 1 5 2
1 1 6 1
1 1 7 0
1 2 0 6
1 2 1 5
1 2 2 4
1 2 3 3
1 2 4 2
1 2 5 1
1 2 6 0
1 3 0 5
1 3 1 4
1 3 2 3
1 3 3 2
1 3 4 1
1 3 5 0
1 4 0 4
1 4 1 3
1 4 2 2
1 4 3 1
1 4 4 0
1 5 0 3
1 5 1 2
1 5 2 1
1 5 3 0
1 6 0 2
1 6 1 1
1 6 2 0
1 7 0 1
1 7 1 0
1 8 0 0
2 0 0 7
2 0 1 6
2 0 2 5
2 0 3 4
2 0 4 3
2 0 5 2
2 0 6 1
2 0 7 0
2 1 0 6
2 1 1 5
2 1 2 4
2 1 3 3
2 1 4 2
2 1 5 1
2 1 6 0
2 2 0 5
2 2 1 4
2 2 2 3
2 2 3 2
2 2 4 1
2 2 5 0
2 3 0 4
2 3 1 3
2 3 2 2
2 3 3 1


### wap ato find those numbers which are divisible by 7 and multiples of 5, between 1500 and 2700

In [3]:
for i in range(1500,2701):
    if(i%7==0&i%5==0):
        print(i)

1505
1512
1519
1526
1533
1540
1547
1554
1561
1568
1575
1582
1589
1596
1603
1610
1617
1624
1631
1638
1645
1652
1659
1666
1673
1680
1687
1694
1701
1708
1715
1722
1729
1736
1743
1750
1757
1764
1771
1778
1785
1792
1799
1806
1813
1820
1827
1834
1841
1848
1855
1862
1869
1876
1883
1890
1897
1904
1911
1918
1925
1932
1939
1946
1953
1960
1967
1974
1981
1988
1995
2002
2009
2016
2023
2030
2037
2044
2051
2058
2065
2072
2079
2086
2093
2100
2107
2114
2121
2128
2135
2142
2149
2156
2163
2170
2177
2184
2191
2198
2205
2212
2219
2226
2233
2240
2247
2254
2261
2268
2275
2282
2289
2296
2303
2310
2317
2324
2331
2338
2345
2352
2359
2366
2373
2380
2387
2394
2401
2408
2415
2422
2429
2436
2443
2450
2457
2464
2471
2478
2485
2492
2499
2506
2513
2520
2527
2534
2541
2548
2555
2562
2569
2576
2583
2590
2597
2604
2611
2618
2625
2632
2639
2646
2653
2660
2667
2674
2681
2688
2695


### wap a program to convert temp from or to c to f of f to c

In [11]:
n=int(input("enter the temprature"))
n1=input("enter the temprature in which state")
if(n1=="c"):
    f=9*((n/5))+(32)
    print(f)
if(n1=="f"):
    c=(n-32)*(5/9)
    print(c)

enter the temprature45
enter the temprature in which statef
7.222222222222222


### wap to guess a no. from  user

In [14]:
n=int(input("enter the no. of guess"))
n1=int(input("enter the no. from user"))
c=1
while(n1!=n):
    c=c+1
    n1=int(input("again entr the no. from user"))
print("this attempts user guess the no.",c)    

enter the no. of guess5
enter the no. from user6
again entr the no. from user9
again entr the no. from user7
again entr the no. from user4
again entr the no. from user5
this attempts user guess the no. 5


In [16]:
n=int(input("enter the no. of guess"))
n1=int(input("entr the no. from user"))
c=1
while(n1!=n):
    c=c+1
    if(n1>n):
        print("enter the lower no.")
    if(n1<n):
        print("enter the greater no.")
    n1=int(input("enter the no. from user"))
print("this attempts user guess the no.",c)    

enter the no. of guess80
entr the no. from user70
enter the greater no.
enter the no. from user75
enter the greater no.
enter the no. from user79
enter the greater no.
enter the no. from user92
enter the lower no.
enter the no. from user90
enter the lower no.
enter the no. from user80
this attempts user guess the no. 6


### wap to print the pattern of stars

In [15]:
n=int(input("enter the maximum no. of stars"))
for r in range(1,n+1):
    for c in range(1,r+1):
        print("*",end=" ")
    print(" ")    
for r in range(1,n+1):       
    for c in range(1,(n+1)-(r)):
        print("*",end=" ")
    print(" ")        

enter the maximum no. of stars8
*  
* *  
* * *  
* * * *  
* * * * *  
* * * * * *  
* * * * * * *  
* * * * * * * *  
* * * * * * *  
* * * * * *  
* * * * *  
* * * *  
* * *  
* *  
*  
 


### wap a program to receive a word from the user and reverse it

In [ ]:
l1=input("enter the word from the user")
for i in range(0,len(l1)):
    for r in range(len(l1)-1,-1,-1):
        r[i]=l1[r]    

### wap a program to count the no. of even or odd no.

In [10]:
c=0
s=0
for i in range(1,10):
    if(i%2==0):
        c=c+1
    else:
        s=s+1
print("the no. of even no. are ",c)
print("the no. of odd no. are ",s)

the no. of even no. are  4
the no. of odd no. are  5


### wap to print all the list elements one by one

In [11]:
datalist=[1452,11.23,1+2j,True,'w3resourse',(0,-1),[5,12],{"class":"v","section":'a'}]
for i in range(0,len(datalist)):
    print(datalist[i],type(datalist[i]))

1452 <class 'int'>
11.23 <class 'float'>
(1+2j) <class 'complex'>
True <class 'bool'>
w3resourse <class 'str'>
(0, -1) <class 'tuple'>
[5, 12] <class 'list'>
{'class': 'v', 'section': 'a'} <class 'dict'>


### wap to print all the no. from 0 to 6 except 3 and 6 with countinue

In [19]:
for i in range(0,7):
    if(i==3 or i==6):
        continue
    print(i)        

0
1
2
4
5


### wap a program to print the fibbonaci series between 0 and 50

In [23]:
a=0
b=1
print(a)
print(b)
for  i in range(1,50):
    c=a+b
    a=b
    b=c
    if(c<50):
        print(c)

0
1
1
2
3
5
8
13
21
34


### wap to print fibbonacci series bw 0 upto 50

In [24]:
a=0
b=1
print(a)
print(b)
for  i in range(1,50):
    c=a+b
    a=b
    b=c
    print(c)

0
1
1
2
3
5
8
13
21
34
55
89
144
233
377
610
987
1597
2584
4181
6765
10946
17711
28657
46368
75025
121393
196418
317811
514229
832040
1346269
2178309
3524578
5702887
9227465
14930352
24157817
39088169
63245986
102334155
165580141
267914296
433494437
701408733
1134903170
1836311903
2971215073
4807526976
7778742049
12586269025


### wap to print the 0 to 50 mulitples of three print "fizz"and five muliples " buzz" and five or three print"fizzbuzz"

In [42]:
for i in range(0,51):
    if(i%3==0 and i%5==0):
        print("fizzbuzz")
    elif(i%3==0):
        print("fizz")
    elif(i%5==0):
        print("buzz")
    else:   
        print(i)    

fizzbuzz
1
2
fizz
4
buzz
fizz
7
8
fizz
buzz
11
fizz
13
14
fizzbuzz
16
17
fizz
19
buzz
fizz
22
23
fizz
buzz
26
fizz
28
29
fizzbuzz
31
32
fizz
34
buzz
fizz
37
38
fizz
buzz
41
fizz
43
44
fizzbuzz
46
47
fizz
49
buzz


### swaping the first and last element of the list

In [1]:
l1=[1,2,3,4,5]
temp=l1[0]
l1[0]=l1[4]
l1[4]=temp
print(l1)

[5, 2, 3, 4, 1]


### python program to swap any two no. in the list

In [7]:
l1=[1,2,3,4,5,6,7,8,9]
a=int(input("enter the no. you want to swap"))
b=int(input("enter the second no. you want to swap"))
for i in range(0,9):
    if(a==l1[i]):
        a=i
    if(b==l1[i]):
        b=i
temp=l1[a]
l1[a]=l1[b]
l1[b]=temp
print(l1)

enter the no. you want to swap1
enter the second no. you want to swap9
[9, 2, 3, 4, 5, 6, 7, 8, 1]


### swap elements in string list

In [9]:
l1=['a','b','c','d','e','f','g','reshav','goyal']
a=input("enter the string you want to swap")
b=input("enter the second string you want to swap")
for i in range(0,len(l1)):
    if(a==l1[i]):
        a=i
    if(b==l1[i]):
        b=i
temp=l1[a]
l1[a]=l1[b]
l1[b]=temp
print(l1)

enter the string you want to swapreshav
enter the second string you want to swapgoyal
['a', 'b', 'c', 'd', 'e', 'f', 'g', 'goyal', 'reshav']


###  wap to find the length of the string

In [11]:
l1=['a','b','c','d','e','f','g','reshav','goyal']
c=0
for i in l1:
    c=c+1
print(c)    

9


### wap to print the maximum of two no. bw the python

In [13]:
a=int(input("enter the first no."))
b=int(input("entr the second n."))
if(a>b):
    print("the a is greater")
    print("the b is lesser")
else:
    print("the b is greater")
    print("the a is lesser")

enter the first no.5
entr the second n.6
the b is greater
the a is lesser


### wap to check element is exist or not in list

In [4]:
l1=['a','b','c','d','e','f','g','reshav','goyal']
n=int(input("enter the no.of times you want to check the no. is present or not"))
for i in range(0,n):
    a=input("enter the element you want to check")
    for i in range(0,len(l1)):
        if(a==l1[i]):
            k=i
    print("the element a is present at",a,k)       

enter the no.of times you want to check the no. is present or not1
enter the element you want to checkd
the element a is present at d 3


### wap to clear a list

In [6]:
l1=['a','b','c','d','e','f','g','reshav','goyal']
for i in range(0,len(l1)):
    l1[i]=0
print(l1)    

[0, 0, 0, 0, 0, 0, 0, 0, 0]


### clear a list using del remove or pop

In [38]:
l1=['a','b','c','d','e','f','g','reshav','goyal']
for i in range(0,len(l1)):
    l1.pop()
print(l1)
l2=['a','b','c','d','e','f','g','reshav','goyal']
for i in range(0,len(l2)):
    i=0
    l2.remove(l2[i])
print(l2)    

[]
[]


# numpy array starting

# syntax

In [3]:
# 1d array
import numpy as np
a=np.array([1,2,3,4])
print(a)# just only give the list of 1,2,3,4
a # this part give the list with written array

# 2d array
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b)
b

# here in this we just creating a numpy array 


[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### methods that use in numpy

In [9]:

b=np.array([[1,2,3,4],[5,6,7,8]])
print("shape", b.shape) # it gives rows and coulums
print("size", b.size) # no. of elements
print("dim",b.ndim) # it gives the dimentions
print("type",b.dtype) # type of the numbers
print(b[1,3])



shape (2, 4)
size 8
dim 2
type int32
8


### concept of zeros ones and empty 

In [22]:
zeros=np.zeros((2,5),dtype=np.int16)
print(zeros)#it gives the array of the zeros
ones=np.ones((2,4),dtype=np.int32)
print(ones)#it gives the array of ones
empty=np.empty((2,3),dtype=np.int32)
print(empty)#it gives the array of random no.

[[0 0 0 0 0]
 [0 0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]]
[[-2019524080         380           0]
 [          0           1 -2147483648]]


## concept of 1d array 
##
### arange method

In [52]:
# when you print an array, NUMPY displays it in a similar way to nested list
a=np.arange(45)
print(a)
print(type(a))
print(a.ndim)

# it just gives only 1 d array





[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44]
<class 'numpy.ndarray'>
1


## concept of 2d array with example

In [1]:
import numpy as np
b=np.arange(45).reshape(9,5)# this reshape function give the 2 d array with 9 rows and 5 coulumns
print(b)

# it just give only us that it just only row and column

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]]


## concept of 3d array with example

In [60]:
b=np.arange(6).reshape(2,1,3)
b

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [ ]:
### the concept of 3d reshape says that (a,b,c)
### c= how many nno. are in one row contains
### b= how many pairs of 1 d in each 2d
### a= how many pairs of 2 d in each 3d

## concept of 4d  with examples

In [47]:
b=np.arange(12).reshape(1,2,3,2)
b

array([[[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]]])

In [48]:
b=np.arange(16).reshape(2,4,1,2)
b

array([[[[ 0,  1]],

        [[ 2,  3]],

        [[ 4,  5]],

        [[ 6,  7]]],


       [[[ 8,  9]],

        [[10, 11]],

        [[12, 13]],

        [[14, 15]]]])

In [49]:
b=np.arange(20).reshape(2,2,1,5)
b

array([[[[ 0,  1,  2,  3,  4]],

        [[ 5,  6,  7,  8,  9]]],


       [[[10, 11, 12, 13, 14]],

        [[15, 16, 17, 18, 19]]]])

In [50]:
c=np.arange(24).reshape(2,2,2,3)
print(c)

[[[[ 0  1  2]
   [ 3  4  5]]

  [[ 6  7  8]
   [ 9 10 11]]]


 [[[12 13 14]
   [15 16 17]]

  [[18 19 20]
   [21 22 23]]]]


### the concept of 4d array says that in reshape(a,b,c,d)
### d= in one row how many no.  contains
### c= c denotes the how many pair of one d array in each 2d array
### b= b denotes the how many pair of 2d array in every three d array
### a= a denotes the how many pair of 3d array in 4d array

#### 

### linespace 

In [62]:
linespace=np.linspace(1,5,12)
linespace
# this will give me a 12 equal distance no. from 1 to 5 

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

### empty

In [66]:
empty=np.empty((2,3))
empty
# this will give me a random no. with 2 rows and 3 coulumns
empty=np.empty((3,))
empty

array([ 8.07482619e-312,  0.00000000e+000, -4.94065646e-324])

### empty like method

In [68]:
emptylike=np.empty_like(linespace)
emptylike
# this method give a same nos that is in bracket

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

### identity

In [69]:
identity=np.identity(6)
identity
# this will give the identiy matrix of n*n

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

### ravel

In [71]:
identity.ravel()
# this is the function or attribute that given the original dim that is 1d array

array([1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 1.])

## various function in python

In [19]:
import numpy as np
a=np.array([[0,2.9,4],[9,4,5]])
b=np.array([[3,4,9],[4,8,5]])
print(a.max())#this will give the maximum no. in array
print(b.max())
print(a.min())# this will give the value of min no in array
print(b.min())
print(a.argmax())# this will give the idex value of max no.
print(a.argmin())# this wil give the idex balue of min no.
c=np.array([[1,2,4,3,5,6],[7,8,9,11,10,12]])
print(c.argsort())# gives the sorted index 
print(a.sum(axis=0))# this will give the sum of rows
print(a.sum(axis=1))# coulums
print(a.T)# transposse of matrix
print(a.argmax(axis=0))# check the rows and give index
print(a.argmax(axis=1))# check coulms

#universal functions
print(np.sqrt(a))
print(np.exp(a))
print(np.add(a,b))
print(np.where(a>1))# this will give index value where a>1
print(type(np.where(a>1)))# this gives the idex in tuple form
print(np.count_nonzero(a))# gives the value of non zeros
print(np.nonzero(a))
print(np.abs(a))# gives the  absoulute value
print(np.fabs(a))#gives floating values
print(np.sign(a))# gives the singn of a no. 1for postive 0 for zero -1 for negative
# a=.9
print(np.rint(a))# it gives the round of value
print(np.modf(a))# it diff the integerand fraction parts
print(np.isnan(a))# it gives the boolean value that indicates the nan
print(np.isnan(b))

9.0
9
0.0
3
3
0
[[0 1 3 2 4 5]
 [0 1 2 4 3 5]]
[9.  6.9 9. ]
[ 6.9 18. ]
[[0.  9. ]
 [2.9 4. ]
 [4.  5. ]]
[1 1 1]
[2 0]
[[0.         1.70293864 2.        ]
 [3.         2.         2.23606798]]
[[1.00000000e+00 1.81741454e+01 5.45981500e+01]
 [8.10308393e+03 5.45981500e+01 1.48413159e+02]]
[[ 3.   6.9 13. ]
 [13.  12.  10. ]]
(array([0, 0, 1, 1, 1], dtype=int64), array([1, 2, 0, 1, 2], dtype=int64))
<class 'tuple'>
5
(array([0, 0, 1, 1, 1], dtype=int64), array([1, 2, 0, 1, 2], dtype=int64))
[[0.  2.9 4. ]
 [9.  4.  5. ]]
[[0.  2.9 4. ]
 [9.  4.  5. ]]
[[0. 1. 1.]
 [1. 1. 1.]]
[[0. 3. 4.]
 [9. 4. 5.]]
(array([[0. , 0.9, 0. ],
       [0. , 0. , 0. ]]), array([[0., 2., 4.],
       [9., 4., 5.]]))
[[False False False]
 [False False False]]
[[False False False]
 [False False False]]


### basic operations

In [77]:
a=np.array([[1,2,4],[3,4,5]])
b=np.array([[3,4,5],[3,4,5]])
print(a+b)
print(a-b)
print(a*b)# this multipication is done in element vise
print(a**2)# this will give us the square of every n o in a 
print(a<4)# this will check all the element conditin is true that true ow false
a=np.array([[1,2,3],[2,3,4],[4,5,3]])
b=np.array([[3,4,5],[3,4,4],[3,3,3]])
print(a.dot(b))# this use matrix multipication

[[ 4  6  9]
 [ 6  8 10]]
[[-2 -2 -1]
 [ 0  0  0]]
[[ 3  8 20]
 [ 9 16 25]]
[[ 1  4 16]
 [ 9 16 25]]
[[ True  True False]
 [ True False False]]
[[18 21 22]
 [27 32 34]
 [36 45 49]]


## indexing ,slicing,iterating

In [37]:
a=np.arange(90).reshape(2,9,5)
print(a)# this will genrate the 2 parts o or 1
print(a[1,...])# this will genrate the 1 part with all values
# it denotes the a,b,c
#a= this denotes the array which you are used
#b=this denotes the row which you are selected
#c=this denotes the column of the array
print(a[:,2,:])
print(a[1,1:3,3:5])
print(a[1,1:3,[3,4]])




[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]]

 [[45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]
  [60 61 62 63 64]
  [65 66 67 68 69]
  [70 71 72 73 74]
  [75 76 77 78 79]
  [80 81 82 83 84]
  [85 86 87 88 89]]]
[[45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]]
[[10 11 12 13 14]
 [55 56 57 58 59]]
[[53 54]
 [58 59]]
[[53 58]
 [54 59]]


## array arithmetic

In [39]:
x=np.arange(4)
print("x=",x)
print("sum=",x+5)
print("sub=",x-5)
print("mul=",x*2)
print("div=",x/2)
print("x//2=",x//2)
print("x**2=",x**2)
print("x%2=",x%2)
print("x-=",-x)

x= [0 1 2 3]
sum= [5 6 7 8]
sub= [-5 -4 -3 -2]
mul= [0 2 4 6]
div= [0.  0.5 1.  1.5]
x//2= [0 0 1 1]
x**2= [0 1 4 9]
x%2= [0 1 0 1]
x-= [ 0 -1 -2 -3]


## broadcasting

In [40]:
a=np.array([[2,3,4],[1,2,3]])
b=np.array([2,3,4])
a+b

array([[4, 6, 8],
       [3, 5, 7]])

In [47]:
a=np.arange(16).reshape(4,4)
b=np.arange(4).reshape(1,4)
a+b
# broadcasting means that the addition is performend whenever the matrix is not mis match but it adds the list only 1 

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14],
       [12, 14, 16, 18]])

### computing using numpy

In [1]:
import numpy as np
l=np.array([1,2,3,4])
print(sum(l))
np.sum(l)
%timeit sum(l)
%timeit np.sum(l)

10
1.09 µs ± 5.27 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
4.12 µs ± 589 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [19]:
# np takes less time to complete there work
# bus other function take more time to completer there work
import numpy as np
sum=0
for i in range(1,5):
    sum=sum+i
print(sum) 
%timeit sum
l=np.array([1,2,3,4])
%timeit np.sum(l)# this is the method for calculating the time of the program 

10
19.4 ns ± 0.121 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)
2.99 µs ± 23.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


##  reading data from csv file

In [32]:
import numpy as np
a="https://raw.githubusercontent.com/sarwansingh/Python/master/ClassExamples/data/student-pass-fail-data.csv"
n1=np.genfromtxt(a,delimiter=",",skip_header=1)
print(n1.shape,n1.ndim)
print(n1)


(1000, 3) 2
[[ 7. 27.  1.]
 [ 2. 43.  0.]
 [ 7. 26.  1.]
 ...
 [ 3. 39.  0.]
 [ 7. 25.  1.]
 [ 5. 37.  0.]]


### writing own images

In [125]:
import numpy as np
from PIL import Image
a=np.arange(0,250,1,np.uint8).reshape(25,10)
print(a)
img=Image.fromarray(a)
img.save("image.png")

[[  0   1   2   3   4   5   6   7   8   9]
 [ 10  11  12  13  14  15  16  17  18  19]
 [ 20  21  22  23  24  25  26  27  28  29]
 [ 30  31  32  33  34  35  36  37  38  39]
 [ 40  41  42  43  44  45  46  47  48  49]
 [ 50  51  52  53  54  55  56  57  58  59]
 [ 60  61  62  63  64  65  66  67  68  69]
 [ 70  71  72  73  74  75  76  77  78  79]
 [ 80  81  82  83  84  85  86  87  88  89]
 [ 90  91  92  93  94  95  96  97  98  99]
 [100 101 102 103 104 105 106 107 108 109]
 [110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129]
 [130 131 132 133 134 135 136 137 138 139]
 [140 141 142 143 144 145 146 147 148 149]
 [150 151 152 153 154 155 156 157 158 159]
 [160 161 162 163 164 165 166 167 168 169]
 [170 171 172 173 174 175 176 177 178 179]
 [180 181 182 183 184 185 186 187 188 189]
 [190 191 192 193 194 195 196 197 198 199]
 [200 201 202 203 204 205 206 207 208 209]
 [210 211 212 213 214 215 216 217 218 219]
 [220 221 222 223 224 225 226 227 228 229]
 [230 231 2